### ISSUE TITLE
Plan A always marked as new upon game launch.

### ISSUE THREAD

**Issue by Shiranui-Izayoi** [klipsey/CadetMod#2]
Basically every time you launch/relaunch the game the Plan A special skill will be marked as new. Even if you currently have it equipped used it in a run before etc. No other abilities are effected by this glitch.

I doubt the issue could be caused by other mods as it only effects this one ability on this one character.

**Comment by DamageMaximo** [comment]
Also happening to me

**Comment by smalllbuddy** [comment]
This bug is so annoying I had to uninstall the mod

**Comment by klipsey** [comment]
Not sure how i fixed it but its fixed on the patch from over a week ago
