### ISSUE TITLE
Gun Still Not Appearing

### ISSUE THREAD

**Issue by smalllbuddy** [klipsey/CadetMod#3]
Update 1.1.5 was supposed to have "Fixed base skin gun not appearing?? (why tf does it keep doing this)" however in the lobby the gun still takes time to appear. I am playing pre sots btw

**Comment by klipsey** [comment]
I dont update for pre sots. also thats just the animation, dont ask me why its like that i didnt animate him lol. the patch in 1.1.5 is a fix for the gun quite literally being non existent no matter what
